name: first work flow unit test

on:
  push:
    branches:
      - 'feature/*'

jobs:
  run-unit-test:
    runs-on: windows-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v6.0.2
       - name: run unit test
         run: mvn test
